### ISSUE TITLE
host_header LB api field support in annotations

### ISSUE THREAD

**Issue by guyguy333** [scaleway/scaleway-cloud-controller-manager#126]
Hi,

Could you add support for host_header LB api field through K8S annotations ?

I would like LB to call my nodes with a specific host but I can't configure it right now with K8S annotations.

Thanks :)

**Comment by Nox-404** [comment]
Hello,
what do you mean by setting a host_header ?

The LB created by the CCM defaults to using TCP loadbalancing and is thus not aware of HTTP headers.
You'll get the header the client provided on your service's endpoint.

Also, as far as I know, LB doesn't provide a way to set headers when forwarding to the backend. (I'm gonna ask around to confirm that)

**Comment by Nox-404** [comment]
Just confirmed that LB doesn't provide a way to set any Headers on the requests forwarded to the backends.

I encourage you to create a ticket on Scaleway's console to further describe your use case and see if we can do something about it.
You can also hop in on our community slack and we'll be more than happy to help.

**Comment by guyguy333** [comment]
Hi @Nox-404,

Thanks for checking. I was talking about HTTP Health Check : https://feature-request.scaleway.com/posts/155/allow-host-header-in-loadbalancer-https-healthchecks

You will find this field in LB API Doc in http_config and https_config of health check : https://www.scaleway.com/en/developers/api/load-balancer/zoned-api/#path-backends-get-a-backend-of-a-given-load-balancer

Maybe more generally, it would be great to set configs for all health check configs with a free "map" or similar

**Comment by Nox-404** [comment]
Oh I see !

I just made a PR to support this field, it won't be released before january though.
If you want to beta test it you can use the image built on the PR or if you're using kapsule you'll need to submit a ticket or ask me with your cluster uuid on slack ;)

**Comment by Nox-404** [comment]
Handling this with a free map would require a lot of string parsing (maybe some yaml/json format)
We'll discuss this for another version maybe (still need to support the legacy modes)

**Comment by guyguy333** [comment]
Thank you, I can wait :)

**Comment by Nox-404** [comment]
@guyguy333 it's available on Kapsule clusters, so feel free to test it out and close this issue if that works for you.

You can use the following annotations on your services:
`service.beta.kubernetes.io/scw-loadbalancer-health-check-type="80:http;443:https"`
`service.beta.kubernetes.io/scw-loadbalancer-health-check-http-uri="80:mydomain.tld/health;443:mydomain2.tld/health"`
