### ISSUE TITLE
Disable loadbalancer

### ISSUE THREAD

**Issue by toonsevrin** [scaleway/scaleway-cloud-controller-manager#13]
We would like to disable the Scaleway LoadBalancer operator. We like to use https://github.com/kontena/akrobateo for our LoadBalancer instantiation.

**Comment by Sh4d1** [comment]
Hey! So I'm not sure we will integrate the option in the CCM 🤔
One way to disable it though can be by setting 
`service.beta.kubernetes.io/scw-loadbalancer-id: dummy`. You'll get some errors though but it'll work @toonsevrin 😄

**Comment by toonsevrin** [comment]
Hehe, I've been setting the type to "asdasd", another reason why I would make the LoadBalancer listener togglable (especially on cluster launch) is because I really do not want to accidentally get billed resources (which has been the case with the loadbalancer when I installed Istio)

**Comment by Sh4d1** [comment]
So yep this is not planned (and no other cloud offer this functionality I guess 😅).
A solution would be to write an admission controller that check created service for a dummy annotation for instance :)

**Comment by toonsevrin** [comment]
All right, it's your choice of course!

**Comment by Sh4d1** [comment]
I'll reopen if we change our decision 😄

**Comment by toonsevrin** [comment]
Sure thing, enjoy your evening!!
