### ISSUE TITLE
Manage internal load balancers

### ISSUE THREAD

**Issue by ndrpnt** [scaleway/scaleway-cloud-controller-manager#131]
Now that cluster can be made "private", an annotation like `service.beta.kubernetes.io/scw-loadbalancer-internal: "true"` could be added to create an [internal load balancer](https://kubernetes.io/docs/concepts/services-networking/service/#internal-load-balancer).

The internal load balancer would behave exactly like its public counterpart, except:
* An ACL dropping all traffic except from within the private network is defined on the load balancer, regardless of whether `spec.loadBalancerSourceRanges` is specified
* Specifying `spec.loadBalancerSourceRanges` does _not_ allow traffic coming from the nodes' public addresses
* `status.loadBalancer.ingress[0].ip` is set to the private IP of the load balancer, retrieved from IPAM, instead of its public IP
* `spec.loadBalancerIP` sets the [`static_config`](https://www.scaleway.com/en/developers/api/load-balancer/zonedapi/#path-private-networks-attach-a-load-balancer-to-a-private-network) field instead of looking for a corresponding flexible IP

**Comment by Nox-404** [comment]
This feature is in progress

**Comment by Nox-404** [comment]
Internal LB are now available with the CCM in version `0.28.0`, see annotation doc:
https://github.com/scaleway/scaleway-cloud-controller-manager/blob/master/docs/loadbalancer-annotations.md#servicebetakubernetesioscw-loadbalancer-private
