### ISSUE TITLE
providerID update

### ISSUE THREAD

**Issue by adrian-dinu** [scaleway/scaleway-cloud-controller-manager#132]
Had to migrate our hosts on scaleway due to the `[Bootscript users: update needed by May 15th, 2023. Ensure a seamless transition.](https://www.scaleway.com/en/docs/compute/instances/troubleshooting/bootscript-eol/)` 

All looks good except that the master is stuck with the old providerID, causing a few issues. Trying to patch it didn't work with `spec.providerID: Forbidden: node updates may not change providerID except from "" to valid` . Trying to set it via --provider-id in kubelet also didn't help. Since this is the mater , can't just leave/join the cluster.

Is there any way to update the providerID after a host upgrade/migration ?

**Comment by jtherin** [comment]
that's more a question for kubernetes than scaleway ccm.
