### ISSUE TITLE
No update of load balancer configuration on annotation update

### ISSUE THREAD

**Issue by samber** [scaleway/scaleway-cloud-controller-manager#145]
When we execute twice our `kubectl apply -f ...` for creating/updating scaleway load balancers, the last change is not applied to LB.

**Comment by jtherin** [comment]
can you give logs of the ccm / svc events ?

**Comment by Nox-404** [comment]
Since there's been no response since November, I'll close that issue.
Feel free to reopen if you need further assistance.
