### ISSUE TITLE
LoadBalancer backend ips get wiped every ~24 hours

### ISSUE THREAD

**Issue by adrian-dinu** [scaleway/scaleway-cloud-controller-manager#16]
I have installed the scaleway-cloud-controller-manager on a Kubernetes cluster we have on scaleway instances. Everything goes really well with one major issue. Once every ~24 hours all Server IPs that are on the Scaleway LoadBalancer get removed somehow. I can't find why this is happening but if I go to the Scaleway console, to the load balancer, I can see no more ips in the Backend Status tab, and then in the Backends tab the backends each backend is missing the IPs of the nodes under Server IPs. If I just manually add them back everything works ok again. 

Do you have any idea what could be causing this or how should I try to debug it ?

**Comment by jtherin** [comment]
Hello, can you send me by mail (jtherin@scaleway.com) your logs of the ccm ?

**Comment by jtherin** [comment]
Hello, thanks for your mail, have you added `--cloud-provider=external` flag on kubelet on your nodes ?
What is the value of ProviderID field of your nodes (kubectl describe nodes)

**Comment by adrian-dinu** [comment]
Adding `--cloud-provider=external` to all the nodes fixed the issue it seems (sorry for this omission on my side, this was an existing cluster). Now I can see the IP in the External-ip node and got an event with `reason: 'UpdatedLoadBalancer' Updated load balancer with new hosts` and the IPs are indeed added to the LB now (interesting that when I added the LB the first time, the IPs where there as well).

Regarding the ProviderID, does this have to be added manually ? I have read a little about the format in the sync.go and added it like:

`kubectl patch node node -p '{"spec":{"providerID":"scaleway://instance/fr-par-1/xxxxx-xxxx-xxx"}}'`

It seems to have removed the `provider ID is empty for node nodex, ignoring` in the logging and no other error regarding it.

Thank you for your help.

**Comment by jtherin** [comment]
ProviderID is normally set by the cloud controller manager for nodes with `--cloud-provider=external` if they are found on instance api. Kubernetes try to find instance by name (node name <> provider instance name) and if found, apply ProviderID.

**Comment by adrian-dinu** [comment]
So it seems since the cloud-provider was missing that step got missed. Adding it manually seems to work ok. No more warning or errors at the moment. Thank you.
