### ISSUE TITLE
LB certs are ignored

### ISSUE THREAD

**Issue by denissabramovs** [scaleway/scaleway-cloud-controller-manager#43]
Doing this on a deployed LB:
`kubectl edit svc traefik-ingress -n kube-system`

Updating certs there:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/scw-loadbalancer-certificate-ids: ee2a9cd5-ca88-4a88-a5e0-263d42121723,07cae1ba-b3e0-45c2-b744-5046b89e86e3,c3b9853a-5185-468c-8e51-e21cd600138d,22442a32-1e81-479d-9446-a4e6794e10f2,03d3465d-17d1-4ec0-be4e-36fd16546fc9,7e64f43b-ffe8-4af0-b469-af0af27165b9
    service.beta.kubernetes.io/scw-loadbalancer-id: fr-par/f3d2fa91-a211-44ee-b986-a2ee7c8afaab

This is not working either:
service.beta.kubernetes.io/scw-loadbalancer-certificate-ids: "443:ee2a9cd5-ca88-4a88-a5e0-263d42121723,07cae1ba-b3e0-45c2-b744-5046b89e86e3,c3b9853a-5185-468c-8e51-e21cd600138d,22442a32-1e81-479d-9446-a4e6794e10f2,03d3465d-17d1-4ec0-be4e-36fd16546fc9,7e64f43b-ffe8-4af0-b469-af0af27165b9"

This too:
service.beta.kubernetes.io/scw-loadbalancer-certificate-ids: "443,80:ee2a9cd5-ca88-4a88-a5e0-263d42121723,07cae1ba-b3e0-45c2-b744-5046b89e86e3,c3b9853a-5185-468c-8e51-e21cd600138d,22442a32-1e81-479d-9446-a4e6794e10f2,03d3465d-17d1-4ec0-be4e-36fd16546fc9,7e64f43b-ffe8-4af0-b469-af0af27165b9"
```

I'm refering this comment from the source code... Couldn't find any relevant info about it in the docs.
https://github.com/scaleway/scaleway-cloud-controller-manager/blob/master/scaleway/loadbalancers.go#L141

Please let us know how we can configure our kubernetes cluster to attach certs properly.
Because each time we update LB or scale cluster, our certificates are removed from LB frontend instance.

Thank you.

**Comment by denissabramovs** [comment]
In scaleway console UI they are not displayed in a particular updated or re-created frontend instance.
Values are accepted, but no certs are attached to above frontend instance inside LB.

**Comment by Sh4d1** [comment]
Do you use it with Kapsule? The latest version is not yet deployed on all clusters. It is on the new ones, and you can trigger a cluster upgrade to the same version in order to get the latest ccm release

**Comment by denissabramovs** [comment]
Yes, with Kapsule.

**Comment by denissabramovs** [comment]
Oh i see now, i'll try to upgrade the cluster, thank you.
Will report if issue has gone.

**Comment by denissabramovs** [comment]
Great, now it is working. Thank you very much!
