### ISSUE TITLE
Loadbalancer aren't created in the same Zone as their k8s pool parent

### ISSUE THREAD

**Issue by rhanka** [scaleway/scaleway-cloud-controller-manager#83]
This bugs appears to the current master code, a seems to be what I consume as a enduser of the Kapsule offer.

When creating a LB through Kapsule, it always go to the defaultZone of the region.

It seems that : `scaleway/loadbalancers.go` doesn't even try to pass a Zone request, although the raw go lib make it possible scaleway-sdk-go/api/lb/v1/lb_sdk.go.

The defaultZone of a loadbalancer controle by this service should be the kapsule parent one and note de "defaultZone" of the region.

This bug makes the option `service.beta.kubernetes.io/scw-loadbalancer-force-internal-ip` unusable for a cluster in the non defaultZone, although it is a profitable security feature (only working in the defaultZone, so).

**Comment by Sh4d1** [comment]
Hello ! We are aware of the issue. Historically the LB API was regionalized, and became zonal a few months ago. We still need to fix this, without breaking the existing ones.

**Comment by rhanka** [comment]
Thank for that information. 
Does this mean this issue is solved in some branch, and that there's only ton plan deployment ? Or that the issue is referenced elsewhere ? Or the issue is not treated in this repository ? 
I would need to go further to know when it will be solve, as i need a dual site deployment and this undocumented asymetry bug breaks the resilient architecture design of my API.

**Comment by Sh4d1** [comment]
> this issue is solved in some branch

not yet, hopefully it wil be implemented this week

**Comment by rhanka** [comment]
Wonderful !! 👏

**Comment by jtherin** [comment]
new annotation added `service.beta.kubernetes.io/scw-loadbalancer-zone` through PR https://github.com/scaleway/scaleway-cloud-controller-manager/pull/86 to specify where the loadbalancer should be created. beware: change does not have effect after creation.

will be deployed on kapsule/kosmos soon.

**Comment by sagikazarmark** [comment]
For the record: the issue seems to occur when everything is in the same zone as well. Manually specifying the zone using the above annotation does the trick.

Might make sense to add it here as well: https://registry.terraform.io/providers/scaleway/scaleway/latest/docs/resources/k8s_cluster

**Comment by jtherin** [comment]
An example was put on terraform documentation too :)
