### ISSUE TITLE
spec: loadBalancerIP fails if IP is not from defaultZone

### ISSUE THREAD

**Issue by rhanka** [scaleway/scaleway-cloud-controller-manager#84]
when applying a loabalancer with:
```
spec:
  loadBalancerIP: ${IP}
```
with IP being a previously reserved IP from non defaultZone (e.g IP from fr-par-2), 
No loadblancer is even ordered.
The option work well when IP is in the defaultZone (e g IP from fr-par-1).

**Comment by Sh4d1** [comment]
This is more or less linked to #83, closing it as resolving #83 will fix this one too.
