### ISSUE TITLE
Privet network in Kubernetes cluster

### ISSUE THREAD

**Issue by sergelogvinov** [scaleway/scaleway-cloud-controller-manager#99]
Hello. 
I'd like to use the privet network in my Kubernetes cluster. Kubelet can register itself using IP from a privet network. And CCM can find the node by name/IP in DHCP lease table (static/dynamic allocated). PR #98 

There are a few questions here:
We can use environment variables like SCW_DEFAULT_VPC_NAME (or ID). To allow CCM search node in the private network.  The SCW_DEFAULT_VPC_NAME - is better for multi-region setups. ID exists in one zone only.

And this env can be used in PR #96 too. If env exists use the default private network, And annotations can overlap this value. 

Can you share your thoughts? @LucasBoisserie @jtherin

**Comment by jtherin** [comment]
Closing. Implemented in #113 using the upcoming ipam api. (documentation soon)
